= c#
:toc: macro
:hp-tags: c#

toc::[]

== classes/méthodes

=== différences c++,c#

* pas de section public, private dans les classes, chaque méthode est préfixée par public, private...
* Héritage public seulement entre les classes
* out, ref pour les paramètres

=== abstract, virtual override

Au niveau le pluys haut, on définit les méthodes soit abstraites (pas de def) soit virtual).

Une méthode redéfinie est override

[source,c#]
----
public virtual decimal CalculatePay()
        {
            return basepay;
        }
----

[source,c#]
----
public override decimal CalculatePay()
{
    return basepay + salesbonus;
}
----

=== out,ref

Utilisé pour les paramètres. 
Un paramètre out n'est pas initialisé.

Pour ref, il doit être initialisé par l'appelant

== types

=== differences c++/c#

* var <=> auto

* array +
[,] pour les array 2 dimensions, [][] pour les jagges array

* les struct sont des *value type*, les classes des *reference type* +
pas de new

=== boxing/unboxing

Boxing::
Encapsuler un type primitif dans un objet. Ce type de value type devient un reference type +
Exemple : pour mettre un int dans une liste d'objet.

[source,c#]
----
double e = 2.7; // boxing
object o = e; // box
double ee = (double)o; // unboxing
----

=== array

* simple

.tableau simle avec initialisation
[source,c#]
----
Shape[] shapes =
{
   new Square(5, "Square #1"),
   new Circle(3, "Circle #1"),
            new Rectangle( 4, 5, "Rectangle #1")
};
----

* multidimensionnel

[source,c#]
----
// Declare a two dimensional array
int[,] multiDimensionalArray1 = new int[2, 3];
----

* jagged

[source,c#]
----
int[][] jaggedArray = new int[6][];

// Set the values of the first array 
jaggedArray[0] = new int[4] { 1, 2, 3, 4 };
----
=== collections(System.Collections.Generic)

* ArrayList : liste d'objets ... Il faut boxer les types primitis et il faut
caster les élément. 

* List<T> => c'est comme un array mais de taille variable
* LinkedList<T>
* Dictionary<key,value>
* SortedDictionar<key,value>
* Stack<T>
* Queue<T>
* HashSet
* SortedSet 

=== iterateurs

* la class iterable

** interface IEnumerable définit GetEnumerator. Une classe peut être enumerable.
** L'interface IEnumerator definit MoveNext, Current, and Reset
** on peut utiliser le *yield return*

[source,c#]
----
public IEnumerator GetEnumerator()
{
    foreach (Animal theAnimal in animals)
    {
        yield return theAnimal.Name;
    }
}
----

=== string

=== nullable (optional)

2 syntaxes possibles:
[source,c#]
Nullable<int> x = null
  
ou  
[source,c#]
int? x = null
  
Ne fonctionne que sur des types valeur, les types références (classe) sont déjà nullables.

On peut appeler les méthodes *HasValue* ou *GetValueOrDefault*

=== var

Déduction automatique de type
[source,c#]
----
var query = from item in source
            where item <= limit
            select item;
----

=== types anonymes
[source,c#]
.definition
----
var v = new { Amount = 108, Message = "Hello" };
----

[source,c#]
.Example d'utilisation
----
var productQuery = 
    from prod in products
    select new { prod.Color, prod.Price };

foreach (var v in productQuery)
{
    Console.WriteLine("Color={0}, Price={1}", v.Color, v.Price);
}
----

== delegate (lambda)

* delegate 

[source,c#]
----
// declaration de type function
public delegate void TestDelegate(string message); 

//exemple de lambda
new Thread(
   delegate() {
   	Console.WriteLine("ok");
   }
).Start();
----

* Func 

*Func* encapsule une fonction/delegate/lambda expression
[source,c#]
----
Func<int,int,int> = delegate(x,y) { return x+y; }
----

Pour une fonction qui retourne void, utiliser *Action*

* lambda expression

.Lambda expression
[source,c#]
----
Func<int,int,int> = ((x,y) => x+y)
----

=== closures

[source,c#]
----
public static Func<int,int> GetAFunc()
{
    var myVar = 1;
    Func<int, int> inc = delegate(int var1)
                            {
                                myVar = myVar + 1;
                                return var1 + myVar;
                            };
    return inc;
}
----

On peut aussi avoir une *delegate = instance. methode_membre*
Le bind avec le this est automatique

== events

[source,c#]
----
// type delegate
public delegate void ChangedEventHandler(object sender, EventArgs e);

// donnee membre event
public event ChangedEventHandler Changed;

// ajout d'un listener, ListChanged est une methode par exemple
List.Changed += new ChangedEventHandler(ListChanged);

// trigger event -> comme un appel de fonction
Changed(this, e);

// detach
 List.Changed -= new ChangedEventHandler(ListChanged);
 
----

== propriétés

[source,c#]
----
class TimePeriod
{
    private double seconds;

    public double Hours
    {
        get { return seconds / 3600; }
        set { seconds = value * 3600; }
    }
}
----

On peut définir des propriétés dans une méthode abstraite, pour définir les getter/setter . Pour une propriété readonly mettre uniquement:

  get()

== indexeur

[source,c#]
----
 public float this[int index] {
     {
        get
        { return temps[index];}

        set
        { temps[index] = value;}
    }
----
    
== attributs

=== definir attribut

* doit dériver de System.Attribute
* on doit définir un AttributeUsage (all, ou simplement pour les classes, méthodes)

[source,c#]
----
[AttributeUsage(AttributeTargets.All)]
public class DeBugInfo : System.Attribute
{
   private int bugNo;
   public string message;
   
   public DeBugInfo(int bg)
   {
      this.bugNo = bg;
   }
  
  public string Message
   {
      get{return message;}
      
      set {message = value;}
   }
}
----

Ici on a des atributs *positionnels* (paramètres obligatoires, doivent respecter ordre et des attributs *nominatifs* (optionnels)

=== appliquer attributs

[source,c#]
----
[DeBugInfo(49, Message = "Unused variable")]
class Rectangle {
}
----

== Linq

* Exécution 

** Exécution différée

Ici la requête est exécutée dans le foreach

[source,c#]
----
var numQuery =
    from num in numbers
    where (num % 2) == 0
    select num;

 // 3. Query execution.
 foreach (int num in numQuery)
 {
       Console.Write("{0,1} ", num);
 }
 ----
 
 ** Exécution immédiate
 On peut exécuter la requête et sauvegarder les résultats
 [source,c#]
----
List<int> numQuery2 =
    (from num in numbers
     where (num % 2) == 0
     select num).ToList();
----

On peut aussi appeler la méthode *Count* sur la requête pour avoir le nombre de résultats
