= c# - 2
:toc: macro

toc::[]
== Memory management




=== Links
http://stackoverflow.com/questions/3038571/whats-the-purpose-of-gc-suppressfinalizethis-in-dispose-method[explications détaillées] +
http://stackoverflow.com/questions/3038571/whats-the-purpose-of-gc-suppressfinalizethis-in-dispose-method[template détaillé dispose]

TIP: On peut considérer que le programmeur doit appeler dispose, qu'il ne doit pas l'oublier. Dans ce cas, seul l'implem de dispose est nécessaire, pas besoin de finaliser l'objet.

=== Finalize

C'est le destructeur qui implémente le finalize. On peut mettre le cleanup des ressources non managées. Lorsqu'il y a un finalize, le garbage collector fait la destruction en 2 passes.

Le finalize est forcément appelé. 

IMPORTANT: on privilegiera l'implémentation d'une méthode Dispose. Si on a un destructeur, on appelera le dispose. La présence d'un destructeur permet d'éviter les oublis de l'appel à Dispose.

.finalize method
[source,c#]
----
~MyResource()      
{
  // Avec le paramètre false, on indique de 
  // ne pas libérer les ressources managées dans le
  // dispose. Ce sera fait par le GC
  Dispose(false);
}
----


=== IDisposal


* méthode dispose +
On peut définir la méthode dispose qui pourra être appelée explicitement.. On peut l'appeler à partir du destructeur.

[source,c#]
----
public void Dispose()
{
   Dispose(true);
   // This object will be cleaned up by the Dispose method.
   // Therefore, you should call GC.SupressFinalize to
   // prevent finalization code for this object
   // from executing a second time.
   GC.SuppressFinalize(this);
 }
 
 protected void Dispose(Boolean from_dispose)
{
 //Free unmanaged resources
 Win32.DestroyHandle(this.CursorFileBitmapIconServiceHandle);

 //Free managed resources too, but only if I'm being called from Dispose
 //(If I'm being called from Finalize then the objects might not exist
 //anymore
 if (from_dispose)  
 {    
      if (this.frameBufferImage != null)
      {
         this.frameBufferImage.Dispose();
         this.frameBufferImage = null;
      }
   }
}
----

== Appel du code C++

=== pin d'un pointeur

UN pointeur managé peut bouger à tout moment. UI faut le fixer, par le mot *fixed= en C# ou *pin_ptr* en C#.

[source,c++]
----
Point pt = new Point();

// Using fixed allows the address of pt members to be taken,
// and "pins" pt so that it is not relocated.

fixed (int* p = &pt.x)
{
   *p = 1;
}       
----
=== Mélange C++ managé/Non managé

En c++ managé, les objets sont alloués via les pointeurs managés (caractère ^) et les pointeurs/références unsafe. Les pointeurs managés (handle) peuvent bouger, il faut les figer pour avoir un pointeur.


=== Marshal explicite

* Le code managé est préfixé de #pragma managed
* Le code non managé est préfixé de #pragma unmanaged
* Les conversions se font avec le module System::Runtime::InteropServices pour le Marshal 
* Il ne faut pas oublier de libérer la mémoire utilisé pour le marshal (cf exemple).

[source,c#]
----
// MarshalANSI1.cpp
// compile with: /clr
#include <iostream>
#include <stdio.h>

using namespace std;
using namespace System;
using namespace System::Runtime::InteropServices;

#pragma unmanaged

void NativeTakesAString(const char* p) {
   printf_s("(native) received '%s'\n", p);
}

#pragma managed

int main() {
   String^ s = gcnew String("sample string");
   IntPtr ip = Marshal::StringToHGlobalAnsi(s);
   const char* str = static_cast<const char*>(ip.ToPointer());

   Console::WriteLine("(managed) passing string...");
   NativeTakesAString( str );

   Marshal::FreeHGlobal( ip );
}
----

Link: *https://msdn.microsoft.com/fr-fr/library/22e4dash.aspx[msdn- marshal]*

=== PInvoke (marshalling automatique)

* Link: *https://msdn.microsoft.com/frfr/library/aa288468%28v=vs.71%29.aspx[msdn-pinvoke]*

* on utilise l'attribut DllImport
* On utilise les attributs MarshalAs où on précise le type C++ correspondant
* Si on ne précise rien, il y a un marshalling par défaut

[source,c#]
----
// Marshal.cs
using System;
using System.Runtime.InteropServices;

class PlatformInvokeTest
{
    [DllImport("msvcrt.dll")]
    public static extern int puts(
        [MarshalAs(UnmanagedType.LPStr)]
        string m);
    [DllImport("msvcrt.dll")]
    internal static extern int _flushall();


    public static void Main() 
    {
        puts("Hello World!");
        _flushall();
    }
}
----

 On peut définir comment une structure est marshallée

[source,c#]
----
 [StructLayout(LayoutKind.Sequential)]
public class LOGFONT 
{ 
    public const int LF_FACESIZE = 32;
    public byte lfPitchAndFamily;
    [MarshalAs(UnmanagedType.ByValTStr, SizeConst=LF_FACESIZE)]
    public string lfFaceName; 
}
----

== Extension methods

Ici, on ajoute une méthode à String. Une méthode existante (concrête) ne peut être étendu, l'extension ne vient qu'en 2sd priorité.+
Ce sont des classes *static* avec mot clef this. +
Le using du namespace d'extension +active ces extensions+
[source,c#]
.add method to string class
----
namespace ExtensionMethods
{
    public static class MyExtensions
    {
        public static int WordCount(this String str)
        {
            return str.Split(new char[] { ' ', '.', '?' }, 
                             StringSplitOptions.RemoveEmptyEntries).Length;
        }
    }   
}
----